# Markdownlint execution configuration
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Create a list of enabled rules
default: true

# Disable specific rules
MD013: false  # Line length
MD024: false  # Multiple headers with same content
MD033: false  # Inline HTML
MD041: false  # First line in file should be a top level header (frontmatter confuses this sometimes)
