#!/bin/sh

# Install VS Code extensions — runs once
# Extension list generated by chezmoi from .chezmoi.toml.tmpl

set -e

# On WSL, VS Code runs on Windows and the Remote-WSL extension manages the
# server and its extensions in ~/.vscode-server. Any 'code' found here is the
# Windows launcher on /mnt/c, which would install desktop extensions into the
# WSL server (dotfiles#437).
if grep -qi microsoft /proc/version 2>/dev/null; then
  echo "WSL detected - skipping VS Code extension installation"
  exit 0
fi

if ! command -v code >/dev/null 2>&1; then
  echo "VS Code not found — skipping extension installation"
  exit 0
fi

EXTLIST="$HOME/.config/vscode-extensions"

if [ ! -f "$EXTLIST" ]; then
  echo "Warning: Extension list not found at $EXTLIST"
  exit 0
fi

echo "Installing VS Code extensions..."

# Read extension list and install (skip empty lines and comments)
grep -v '^#' "$EXTLIST" | grep -v '^$' | while read -r ext; do
  echo "Installing $ext..."
  code --install-extension "$ext" --force || echo "Warning: Failed to install $ext"
done

echo "VS Code extension installation complete"
