#!/bin/sh

# Install VS Code extensions — runs once
# Extension list generated by chezmoi from .chezmoi.toml.tmpl

set -e

if ! command -v code >/dev/null 2>&1; then
  echo "VS Code not found — skipping extension installation"
  exit 0
fi

EXTLIST="$HOME/.config/vscode-extensions"

if [ ! -f "$EXTLIST" ]; then
  echo "Warning: Extension list not found at $EXTLIST"
  exit 0
fi

echo "Installing VS Code extensions..."

# Read extension list and install (skip empty lines and comments)
grep -v '^#' "$EXTLIST" | grep -v '^$' | while read -r ext; do
  echo "Installing $ext..."
  code --install-extension "$ext" --force || echo "Warning: Failed to install $ext"
done

echo "VS Code extension installation complete"
